spring.application.name=Quiz Backend

# PostgreSQL Konfiguration
spring.datasource.url=jdbc:postgresql://localhost:5434/quiz_multiuser_app
spring.datasource.username=quiz_user
spring.datasource.password=quiz_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto= update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# Mindestens 256 Bit (32 Zeichen) für HS256
# Mindestens 256 Bit (32 Zeichen) für HS256
jwt.secret=9a67471a986613714436e1f0b094607b322a363d63c22420f83f0607a0986598



logging.level.org.springframework.beans=DEBUG
logging.level.org.springframework.context=DEBUG



# Token Gültigkeit in Millisekunden
# 86400000 ms = 24 Stunden = 60*60*24*1000
jwt.expiration=86400000

# Server
server.port=8080