spring.application.name=Quiz Backend

# PostgreSQL Konfiguration
spring.datasource.url=jdbc:postgresql://localhost:5434/quiz_multiuser_app
spring.datasource.username=quiz_user
spring.datasource.password=quiz_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# Mindestens 256 Bit (32 Zeichen) für HS256
jwt.secret=MeinSuperGeheimesSecretDasSehrLangIstUndMindestens256BitHat123456789

# Token Gültigkeit in Millisekunden
jwt.expiration=86400000

# Server
server.port=8080